name: Build Docs (reusable)
on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Add mainpage title to README
        run: sed -i '1s/^/# ReadMe \n\n/' README.md

      - name: Build docs
        run: doxygen .github/workflows/Doxyfile

      - name: Prepare artifact
        run: |
          mkdir -p public-docs
          cp -r docs/html/* public-docs/

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: public-docs
